fix missing mip maps update in the core embedded data
torandi/HzDTextureExplorer pull request #2
Opened 2023-11-16 14:57 UTC by mithkr

lower level mip maps of a DDS texture are embbeded in the core file. During texture replacement the StreamData and the EmbeddedData needs to be replaced with the mip maps from the DDS image.

2023-12-02 01:59 UTC, JohnnyDazzling commented
Exellent work! 10/10

2023-12-07 12:53 UTC, torandi requested changes

2023-12-07 12:53 UTC, torandi commented on HzdTextureExplorer.sln
I guess this is not needed for the change? Please revert.

2023-12-07 12:54 UTC, torandi commented
Seems like a good change in general, thanks! If not needed for the change, can you remove the sln file, as it downgrades VS version to 16 (from 17).

2023-12-08 10:41 UTC, mithkr commented on HzdTextureExplorer.sln
I can remove or at least change the VS version string back. But it is not a downgrade to version 16 is is upgrade to version 17. The origin file was created with VS version 16. Do you than still think I should revert if it's a upgrade?

2023-12-11 12:08 UTC, torandi commented on HzdTextureExplorer.sln
Ah right. No, then let's keep it. I must have been tired when reading the change the first time :)

2023-12-11 12:08 UTC, torandi approved these changes

2023-12-11 12:08 UTC, merged

2023-12-11 12:09 UTC, torandi commented
Pull request merged. Thanks for the fixes. I'll produce a new "official" release soon.

2023-12-28 08:37 UTC, mithkr commented
When will you provide new "official" release?

2023-12-31 12:40 UTC, BenIronW commented
Will you fix the loading error "Invalid magic in texture" ?
Think it is caused by HZD core files, with ElmageCompressionMethod.

2023-12-31 17:18 UTC, mithkr commented
See my pull request https://github.com/torandi/HzDTextureExplorer/pull/3#issue-2061029093